import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="header" id="header">
          <div className="container">
            <a href="#" className="logo">
              Soliman
            </a>
            <ul className="main-nav">
              <li>
                <a href="#articles">Articles</a>
              </li>
              <li>
                <a href="#gallery">Gallery</a>
              </li>
              <li>
                <a href="#features">Features</a>
              </li>
              <li>
                <a href="#">Other Links</a>

                <div className="mega-menu">
                  <div className="image">
                    <img src="imgs/megamenu.png" alt="" />
                  </div>
                  <ul className="links">
                    <li>
                      <a href="#testimonials">
                        <i className="far fa-comments fa-fw"></i> Testimonials
                      </a>
                    </li>
                    <li>
                      <a href="#team">
                        <i className="far fa-user fa-fw"></i> Team Members
                      </a>
                    </li>
                    <li>
                      <a href="#services">
                        <i className="far fa-building fa-fw"></i> Services
                      </a>
                    </li>
                    <li>
                      <a href="#our-skills">
                        <i className="far fa-check-circle fa-fw"></i> Our Skills
                      </a>
                    </li>
                    <li>
                      <a href="#work-steps">
                        <i className="far fa-clipboard fa-fw"></i> How It Works
                      </a>
                    </li>
                  </ul>
                  <ul className="links">
                    <li>
                      <a href="#events">
                        <i className="far fa-calendar-alt fa-fw"></i> Events
                      </a>
                    </li>
                    <li>
                      <a href="#pricing">
                        <i className="fas fa-server fa-fw"></i> Pricing Plans
                      </a>
                    </li>
                    <li>
                      <a href="#video">
                        <i className="far fa-play-circle fa-fw"></i> Top Videos
                      </a>
                    </li>
                    <li>
                      <a href="#stats">
                        <i className="far fa-chart-bar fa-fw"></i> Stats
                      </a>
                    </li>
                    <li>
                      <a href="#discount">
                        <i className="fas fa-percent fa-fw"></i> Request A
                        Discount
                      </a>
                    </li>
                  </ul>
                </div>
              </li>
            </ul>
          </div>
        </div>
        {children}
        <div className="footer">
          <div className="container">
            <div className="box">
              <h3>Soliman</h3>
              <ul className="social">
                <li>
                  <a href="#" className="facebook">
                    <i className="fab fa-facebook-f"></i>
                  </a>
                </li>
                <li>
                  <a href="#" className="twitter">
                    <i className="fab fa-twitter"></i>
                  </a>
                </li>
                <li>
                  <a href="#" className="youtube">
                    <i className="fab fa-youtube"></i>
                  </a>
                </li>
              </ul>
              <p className="text">
                Lorem ipsum, dolor sit amet consectetur adipisicing elit.
                Temporibus nulla rem, dignissimos iste aspernatur
              </p>
            </div>
            <div className="box">
              <ul className="links">
                <li>
                  <a href="#">Important Link 1</a>
                </li>
                <li>
                  <a href="#">Important Link 2</a>
                </li>
                <li>
                  <a href="#">Important Link 3</a>
                </li>
                <li>
                  <a href="#">Important Link 4</a>
                </li>
                <li>
                  <a href="#">Important Link 5</a>
                </li>
              </ul>
            </div>
            <div className="box">
              <div className="line">
                <i className="fas fa-map-marker-alt fa-fw"></i>
                <div className="info">
                  Egypt, Giza, Inside The Sphinx, Room Number 220
                </div>
              </div>
              <div className="line">
                <i className="far fa-clock fa-fw"></i>
                <div className="info">Business Hours: From 10:00 To 18:00</div>
              </div>
              <div className="line">
                <i className="fas fa-phone-volume fa-fw"></i>
                <div className="info">
                  <span>+20123456789</span>
                  <span>+20198765432</span>
                </div>
              </div>
            </div>
            <div className="box footer-gallery">
              <img src="imgs/gallery-01.png" alt="" />
              <img src="imgs/gallery-02.png" alt="" />
              <img src="imgs/gallery-03.jpg" alt="" />
              <img src="imgs/gallery-04.png" alt="" />
              <img src="imgs/gallery-05.jpg" alt="" />
              <img src="imgs/gallery-06.png" alt="" />
            </div>
          </div>
          <p className="copyright">Made With &lt;3 By Soliman</p>
        </div>
      </body>
    </html>
  );
}
